[package]
name = "guber-wire"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.186"
quick-xml = { version = "0.39.2", features = ["async-tokio", "serialize"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
sysinfo = { version = "0.30.13", default-features = false }
tokio = { version = "1.52.1", default-features = false, features = ["time", "sync", "rt", "rt-multi-thread", "macros"] }

[dev-dependencies]
